---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-coinFK1-deployment
  labels:
    app: nginx-coinFK1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-coinFK1
  template:
    metadata:
      labels:
        app: nginx-coinFK1
    spec:
      containers:
        - name: nginx-coinFK1
      image: alstsk/nginx-coinFK1:v1
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-coinFK1-service
spec:
  selector:
    app: nginx-coinFK1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
