---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ace-gam2
  labels:
    app: nginx-ace-gam2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ace-gam2
  template:
    metadata:
      labels:
        app: nginx-ace-gam2
    spec:
      containers:
        - name: nginx-ace-gam2
          image: alstsk/nginx-ace-gam2:v3
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ace-gam2
spec:
  selector:
    app: nginx-ace-gam2
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
